config/routes.rb
Rails.application.routes.draw do

  resources :books
  resources :notes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "sessions#welcome"
  get 'auth/github/callback', to: 'sessions#create'
  get '/home', to: "sessions#home" , as: 'home'
  devise_for :users

  resources :books do
  	resources :notes, only: [:new, :create , :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :notes
	validates :name, presence: true

	accepts_nested_attributes_for :notes
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :content, presence: true , length: {in: 1..200}
	#validates :public, presence: true
	validates_associated :book
	accepts_nested_attributes_for :book

	scope :public_notes, -> {where(public: true)}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def new
		@book = Book.new
	end

	def show
		@book = Book.find(params[:id])
	end

	def create
		@book = Book.create(book_params)
	
		

		redirect_to book_path(@book)

	end

	def index
		@books = Book.all		
	end
	
	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		@book.update(book_params)

		redirect_to book_path(@book)
	end

	def destroy
		@book =Book.find(params[:id])
		@book.destroy

		redirect_to books_path
	end

	private

	def book_params
		params.require(:book).permit(:name)
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
		if params[:book_id] && book = Book.find_by_id(params[:book_id])
			@notes = book.notes.public_notes
		else
			@notes = current_user.notes
		end
	end

	def new
		if params[:book_id] && book = Book.find_by_id(params[:book_id])
			@note = book.notes.build			
		else
			@note = Note.new
			@note.build_book
		end
	end

	def create
		@note = current_user.notes.build(notes_params)
		if @note.save
			redirect_to note_path(@note)
		else
			@note.build_book unless @note.book
			render :new
		end
	end

	def show
		set_note
		@book = Book.find_by_id(@note.book_id)
	end

	def edit
		set_note
	end

	def update
		set_note

		@note.update(notes_params)

		redirect_to note_path(@note)
	end

	def destroy
	set_note
		@note.destroy

		redirect_to notes_path
	end

	private

	def set_note
		@note = Note.find_by_id(params[:id])
		if !@note
			redirect_to notes_path
		end
	end

	def notes_params
		params.require(:note).permit(:content, :public, :book_id, book_attributes: [:name])
	end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController

	private 
	def sign_up_params
		params.require(:user).permit(:email ,:password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit(:email ,:password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def home
		if user_signed_in?
			@user = current_user
			render :home
		else
			redirect_to welcome_path
		end
	end

	def welcome
		if user_signed_in?
			redirect_to home_path
		else
			render :welcome
		end
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/books/index.html.erb
<h1>All Books</h1>
<% @books.each do |book| %>
<%= link_to book.name, book_notes_path(book) %> <br>

<% end %>

app/views/books/new.html.erb
<h1>
	Create a new Book
</h1>

<%= form_for @book do |f| -%>
	<%= f.label :name %>
	<%= f.text_field :name %>


	<%= f.submit "Create Book" %>
	<% end %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>

<a href="/books/<%= @book.id %>/notes/new">Add Note to this Book</a>
<h4>Notes</h4>

<ol>
<% @book.notes.each do |note| %>
<li> <%= link_to(note.content, note_path(note)) %></li> <br>
<% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NotebookForReaders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render :partial => "sessions/nav" %>
    <%= render :partial => "sessions/nav2" if user_signed_in? %>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |f| -%>
	<%= f.label :content %>
	<%= f.text_field :content %>

	<%= f.label :public, "Public" %>
	<%= f.check_box :public %>

	<br><br>

	<%= f.label :book_id, "Select a Book" %>
	<%= f.collection_select :book_id, Book.all, :id , :name , promp: true %>

	<br><br>


	<%= f.submit %>

<% end -%>

app/views/notes/index.html.erb
<h1>Notes by <%= current_user.email %></h1>
<ol>
<% @notes.each do |note| %>
<div>
<li> <%= link_to note.content, note_path(note)%> <br><span> Book Name - <%= link_to note.book.name, book_path(note.book)  %></span></li><br>

</div>
<% end %>
</ol>

app/views/notes/new.html.erb
<h1>Create a note</h1>
<%= render 'form' %>

app/views/notes/show.html.erb
<h1>Book Name: <%= link_to @book.name, book_path(@book) %></h1>
<h2><%= @note.content %></h1>